# Generated by Django 4.1 on 2025-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_chat', '0013_individualmessagestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptenantdata',
            name='hop_nodes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
