# Generated by Django 4.1 on 2026-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp_chat", "0014_whatsapptenantdata_hop_nodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptenantdata",
            name="edges",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsapptenantdata",
            name="flow_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="whatsapptenantdata",
            name="nodes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsapptenantdata",
            name="start_node_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
