# Generated by Django 4.1 on 2026-02-02 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0007_tenant_agents"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no", models.CharField(db_index=True, max_length=20)),
                (
                    "flow_name",
                    models.CharField(
                        db_index=True, default="interviewdrishtee", max_length=100
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "candidate_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "calibration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=50),
                ),
                (
                    "question1",
                    models.TextField(
                        blank=True, help_text="Audio file URL or media ID", null=True
                    ),
                ),
                (
                    "question2",
                    models.TextField(
                        blank=True, help_text="Audio file URL or media ID", null=True
                    ),
                ),
                (
                    "question3",
                    models.TextField(
                        blank=True, help_text="Audio file URL or media ID", null=True
                    ),
                ),
                (
                    "question4",
                    models.TextField(
                        blank=True, help_text="Audio file URL or media ID", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_responses",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Response",
                "verbose_name_plural": "Interview Responses",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="interviewresponse",
            index=models.Index(
                fields=["tenant", "flow_name", "-timestamp"],
                name="interviews__tenant__10c551_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewresponse",
            index=models.Index(
                fields=["phone_no", "-timestamp"], name="interviews__phone_n_408638_idx"
            ),
        ),
    ]
