# Generated by Django 4.1 on 2026-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0002_interviewresponse_address_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewresponse",
            name="calibration",
            field=models.TextField(blank=True, null=True),
        ),
    ]
