# Generated by Django 4.1 on 2026-02-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0008_invitecode"),
        ("interviews", "0003_alter_interviewresponse_calibration"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresponse",
            name="interview_type",
            field=models.CharField(
                choices=[("vidushi", "Vidushi"), ("maan_vidushi", "Maan Vidushi")],
                db_index=True,
                default="vidushi",
                help_text="Type of interview: Vidushi or Maan Vidushi",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="part1_audio",
            field=models.URLField(
                blank=True,
                help_text="Azure Blob Storage URL for Part 1 audio (Q1-Q3 for Vidushi, Q1-Q4 for Maan Vidushi)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="part2_audio",
            field=models.URLField(
                blank=True,
                help_text="Azure Blob Storage URL for Part 2 audio (Q4-Q6 for Vidushi, Q5-Q8 for Maan Vidushi)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="submission_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of submission", null=True
            ),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="Browser user agent string", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="calibration_audio",
            field=models.URLField(
                blank=True,
                help_text="Azure Blob Storage URL for Q0 calibration audio (Parts A, B, C combined)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="candidate_name",
            field=models.CharField(
                blank=True,
                help_text="Full name of the candidate",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="flow_name",
            field=models.CharField(
                db_index=True, default="naad_2.0_interview", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="phone_no",
            field=models.CharField(
                db_index=True, help_text="Candidate phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("reviewed", "Reviewed"),
                ],
                db_index=True,
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_responses",
                to="tenant.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewresponse",
            index=models.Index(
                fields=["interview_type", "status", "-timestamp"],
                name="interviews__intervi_4c1d46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewresponse",
            index=models.Index(
                fields=["candidate_name", "-timestamp"],
                name="interviews__candida_7ed027_idx",
            ),
        ),
    ]
