# Generated by Django 4.1 on 2026-02-27 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.utils import timezone


def create_default_plans(apps, schema_editor):
    Plan = apps.get_model("tenant", "Plan")
    PlanQuota = apps.get_model("tenant", "PlanQuota")

    plan_definitions = [
        {
            "name": "Base",
            "slug": "base",
            "description": "Frictioned starter experience with limited uploads, templates, and broadcasts.",
            "billing_interval": "monthly",
            "price_cents": 0,
            "currency": "USD",
            "features": {
                "flow_builder": False,
                "priority_support": False,
                "upload_priority": False,
                "api_access": False,
            },
        },
        {
            "name": "Momentum",
            "slug": "momentum",
            "description": "Priority queue for uploads and broadcasts, full Flow Builder access, and responsive support.",
            "billing_interval": "monthly",
            "price_cents": 9900,
            "currency": "USD",
            "features": {
                "flow_builder": True,
                "priority_support": True,
                "upload_priority": True,
                "api_access": True,
                "flow_automation": True,
            },
        },
        {
            "name": "Enterprise Hunt",
            "slug": "enterprise-hunt",
            "description": "Custom contracts, unlimited media, dedicated onboarding, and SLA-backed support.",
            "billing_interval": "custom",
            "price_cents": 0,
            "currency": "USD",
            "features": {
                "flow_builder": True,
                "priority_support": True,
                "upload_priority": True,
                "api_access": True,
                "dedicated_csm": True,
                "custom_quotas": True,
            },
        },
    ]

    created = {}
    for definition in plan_definitions:
        plan = Plan.objects.create(
            id=uuid.uuid4(),
            **definition
        )
        created[definition["slug"]] = plan

    quota_definitions = [
        {"plan_slug": "base", "quota_key": "template_creations", "value": 5, "unit": "templates/month", "enforcement": "soft", "description": "Base tier allows a handful of template submissions."},
        {"plan_slug": "base", "quota_key": "broadcasts_per_day", "value": 2, "unit": "runs/day", "enforcement": "soft"},
        {"plan_slug": "base", "quota_key": "video_uploads_per_day", "value": 1, "unit": "uploads/day", "enforcement": "soft"},
        {"plan_slug": "base", "quota_key": "tickets_per_month", "value": 1, "unit": "tickets/month", "enforcement": "soft"},

        {"plan_slug": "momentum", "quota_key": "template_creations", "value": 50, "unit": "templates/month", "enforcement": "soft"},
        {"plan_slug": "momentum", "quota_key": "broadcasts_per_day", "value": 20, "unit": "runs/day", "enforcement": "soft"},
        {"plan_slug": "momentum", "quota_key": "video_uploads_per_day", "value": 10, "unit": "uploads/day", "enforcement": "soft"},
        {"plan_slug": "momentum", "quota_key": "tickets_per_month", "value": 10, "unit": "tickets/month", "enforcement": "soft"},
        {"plan_slug": "momentum", "quota_key": "automation_executions_per_hour", "value": 10, "unit": "runs/hour", "enforcement": "soft"},

        {"plan_slug": "enterprise-hunt", "quota_key": "template_creations", "value": None, "unit": "templates/month", "enforcement": "strict"},
        {"plan_slug": "enterprise-hunt", "quota_key": "broadcasts_per_day", "value": None, "unit": "runs/day", "enforcement": "strict"},
        {"plan_slug": "enterprise-hunt", "quota_key": "video_uploads_per_day", "value": None, "unit": "uploads/day", "enforcement": "strict"},
        {"plan_slug": "enterprise-hunt", "quota_key": "tickets_per_month", "value": None, "unit": "tickets/month", "enforcement": "strict"},
        {"plan_slug": "enterprise-hunt", "quota_key": "automation_executions_per_hour", "value": None, "unit": "runs/hour", "enforcement": "strict"},
    ]

    for quota in quota_definitions:
        PlanQuota.objects.create(
            plan=created[quota["plan_slug"]],
            quota_key=quota["quota_key"],
            value=quota["value"],
            unit=quota["unit"],
            enforcement=quota["enforcement"],
            description=quota.get("description", ""),
        )


def remove_default_plans(apps, schema_editor):
    Plan = apps.get_model("tenant", "Plan")
    Plan.objects.filter(slug__in=["base", "momentum", "enterprise-hunt"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0008_invitecode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, default=uuid.uuid4, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("billing_interval", models.CharField(choices=[("monthly", "Monthly"), ("annual", "Annual"), ("custom", "Custom")], default="monthly", max_length=20)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlanQuota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quota_key", models.CharField(max_length=60)),
                ("value", models.BigIntegerField(blank=True, null=True)),
                ("unit", models.CharField(default="count", max_length=30)),
                ("enforcement", models.CharField(choices=[("soft", "Soft"), ("strict", "Strict")], default="soft", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quotas", to="tenant.plan")),
            ],
            options={
                "unique_together": {("plan", "quota_key")},
            },
        ),
        migrations.CreateModel(
            name="TenantPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("status", models.CharField(choices=[("active", "Active"), ("trialing", "Trialing"), ("past_due", "Past Due"), ("canceled", "Canceled")], default="active", max_length=20)),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=200, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("next_billing_at", models.DateTimeField(blank=True, null=True)),
                ("effective_features", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.plan")),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_plan", to="tenant.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="TenantQuotaUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quota_key", models.CharField(max_length=60)),
                ("period_start", models.DateTimeField(default=timezone.now)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("used", models.BigIntegerField(default=0)),
                ("threshold_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quota_usage", to="tenant.tenant")),
            ],
            options={
                "unique_together": {("tenant", "quota_key", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="QuotaOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quota_key", models.CharField(max_length=60)),
                ("value", models.BigIntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quota_overrides", to="tenant.tenant")),
            ],
            options={
                "unique_together": {("tenant", "quota_key")},
            },
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("upgrade", "Upgrade"), ("downgrade", "Downgrade"), ("overage", "Overage"), ("payment", "Payment"), ("invoice", "Invoice")], max_length=30)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="billing_events", to="tenant.tenant")),
            ],
        ),
        migrations.RunPython(create_default_plans, reverse_code=remove_default_plans),
    ]
