# Generated by Django 4.1 on 2026-01-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interaction", "0006_conversation_encrypted_message_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="media_caption",
            field=models.TextField(
                blank=True, help_text="Caption for image/video", null=True
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="media_filename",
            field=models.CharField(
                blank=True, help_text="Original filename", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="Azure Blob Storage URL",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="message_type",
            field=models.CharField(
                blank=True,
                help_text="text, image, video, audio, document",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="Thumbnail URL for videos",
                max_length=500,
                null=True,
            ),
        ),
    ]
