# Generated by Django 3.2.25 on 2025-06-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_temps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplate',
            name='trigger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
