# Generated by Django 4.1 on 2026-01-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interaction", "0007_add_media_support_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="business_phone_number_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="contact_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="date_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="source",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["contact_id", "business_phone_number_id", "source"],
                name="conv_contact_bpid_source_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["contact_id", "date_time"], name="conv_contact_datetime_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["tenant", "date_time"], name="conv_tenant_datetime_idx"
            ),
        ),
    ]
