"""
Django settings for simplecrm project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import multiprocessing  # Add this import
import os
from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from corsheaders.defaults import default_headers

ALLOWED_HOSTS = [
"*"
]

def _env_list(name, default):
    """Read a comma-separated env var into a Python list; fall back to default."""
    raw = os.environ.get(name, "")
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    return parts or default

_DEFAULT_ORIGINS = [
    "https://nuren.ai",
    "https://www.nuren.ai",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
]

CSRF_TRUSTED_ORIGINS = list(set(
    _env_list("CSRF_TRUSTED_ORIGINS", _DEFAULT_ORIGINS) + [
        "https://api.nuren.ai",
        "https://nuren.ai",
        "https://www.nuren.ai",
    ]
))

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = list(set(
    _env_list("CORS_ALLOWED_ORIGINS", _DEFAULT_ORIGINS) + _DEFAULT_ORIGINS
))

# Match any Vercel preview deployment URL (each deploy gets a unique hostname).
# Without this, every preview URL would need to be added to the env explicitly.
# This is bounded by 'allow_credentials=True' so the wildcard isn't exploitable
# in the same way as origins=['*'] — the regex match still ends up as a single
# echoed origin in the response.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
    r"^https://.*\.nuren\.ai$",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
"X-Tenant-Id",
    "Authorization",
    "X-CSRFToken",
    "X-Requested-With",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '77fy+^i(n=2)tq$0)&31d@uf3t+ge##$aclyla&lmr@lpinc1&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


JWT_SECRET = os.environ.get("JWT_SECRET", "whatsapp-business-automation-jwt-secret-2026-change-in-production")
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_LIFETIME = 60 * 60  # 1 hour
JWT_REFRESH_TOKEN_LIFETIME = 60 * 60 * 24 * 30  # 30 days

OAUTH_CLIENTS = {
    "frontend": {
        "client_secret": os.environ.get("FRONTEND_SECRET", "frontend-secret"),
        "redirect_uri": "https://yourfrontend.com/callback"
    },
    "crm_example": {
        "client_secret": os.environ.get("CRM_SECRET", "crm-secret"),
        "redirect_uri": "https://crm.com/oauth/callback"
    }
}
# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contacts',
    'interaction',
    'rest_framework',
    'corsheaders',
    'simplecrm',
    'tenant',
    'custom_fields',
    'node_temps',
    'dynamic_entities',
    'analytics',
    'communication',
    'topicmodelling',
    'whatsapp_chat',
    'shop',
    'orders',
    'whatsapp_campaigns',
    'subscriptions',
    'facebook_flows',
    'inventory',
    'wabits',
    'interviews.apps.InterviewsConfig',
]


MIDDLEWARE = [
    # CRITICAL: Connection cleanup MUST be first to ensure connections close after EVERY request
    'simplecrm.middleware.ConnectionCleanupMiddleware',
    'simplecrm.jwt_auth_middleware.JWTAuthMiddleware',
    'simplecrm.tenant_bridge.TenantBridgeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simplecrm.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simplecrm.middleware.LogRequestTimeMiddleware',
]
# settings.py
import os


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {funcName}:{lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # Rotating to prevent disk fill
            'filename': os.path.join(BASE_DIR, 'requests.log'),
            'formatter': 'verbose',
            'maxBytes': 10 * 1024 * 1024,  # 10MB per file
            'backupCount': 5,  # Keep 5 backup files
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # Rotating to prevent disk fill
            'filename': os.path.join(BASE_DIR, 'celery.log'),
            'formatter': 'detailed',
            'maxBytes': 10 * 1024 * 1024,  # 10MB per file
            'backupCount': 5,  # Keep 5 backup files
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        '__main__': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['celery_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery.task': {
            'handlers': ['celery_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'simplecrm': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# LOGGING = {
#      'version': 1,
#      'disable_existing_loggers': False,
#      'handlers': {
#          'console': {
#              'level': 'DEBUG',  # Set the desired log level
#              'class': 'logging.StreamHandler',
#          },
#      },
#      'loggers': {
#          'django': {
#              'handlers': ['console'],
#              'level': 'DEBUG',
#              'propagate': True,
#          },
#          'simplecrm': {  # Replace 'yourapp' with the actual app name
#              'handlers': ['console'],
#              'level': 'DEBUG',
#              'propagate': True,
#          },
#      },
#  }

AUTH_USER_MODEL = 'simplecrm.CustomUser'

ROOT_URLCONF = 'simplecrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simplecrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# =============================================================================
# PERMANENT FIX: PgBouncer Connection Pooling (RECOMMENDED)
# =============================================================================
# Azure PostgreSQL Flexible Server has built-in PgBouncer on port 6432
# This MUST be enabled in Azure Portal for this to work:
#   Azure Portal → PostgreSQL → Server Parameters → pgbouncer.enabled = true
#
# Benefits of PgBouncer:
# - Handles connection pooling at database level
# - Supports 1000s of app connections with only ~100 DB connections
# - Eliminates "remaining connection slots" errors permanently
# =============================================================================

# DEFAULT TO FALSE - Only use PgBouncer if explicitly enabled AND confirmed in Azure Portal
# To enable: Azure Portal → PostgreSQL → Server Parameters → pgbouncer.enabled = true
# Then set USE_PGBOUNCER=true in Azure App Service Configuration
USE_PGBOUNCER = os.environ.get('USE_PGBOUNCER', 'false').lower() == 'true'

# Port selection: env var override > PgBouncer toggle > direct PostgreSQL
DB_PORT = os.environ.get('DB_PORT', '6432' if USE_PGBOUNCER else '5432')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'nurenpostgres_Whatsapp'),
        'USER': os.environ.get('DB_USER', 'nurenai'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Biz1nurenWar*'),
        'HOST': os.environ.get('DB_HOST', 'nurenaistore.postgres.database.azure.com'),
        'PORT': DB_PORT,
        'OPTIONS': {
            'sslmode': 'disable',
            'connect_timeout': 10,
        },
        # PgBouncer transaction mode requires CONN_MAX_AGE=0; direct mode can reuse connections
        'CONN_MAX_AGE': 0 if USE_PGBOUNCER else 60,
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
STATIC_URL = '/static/'



ASGI_APPLICATION = 'simplecrm.asgi.application'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'


# Upload size caps.
#
# Django's defaults are 2.5 MB for both DATA_UPLOAD_MAX_MEMORY_SIZE (total
# request body size — raises RequestDataTooBig past this) and
# FILE_UPLOAD_MAX_MEMORY_SIZE (where individual file uploads spill from
# memory to a tempfile on disk).
#
# Naad 2.0 interview submissions are 5-15 MB of webm/opus audio across
# three parts; longer formats with 2 min/question can reach ~25 MB. The
# generic /interviews/files/upload/ accepts arbitrary user files. 60 MB
# covers both with headroom; Nginx caps at 50 MB upstream so the wall
# is enforced there with a clean 413 the frontend can surface.
DATA_UPLOAD_MAX_MEMORY_SIZE = 60 * 1024 * 1024   # 60 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB — files bigger than
                                                  # this stream to a tempfile
                                                  # via TemporaryFileUploadHandler
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000              # default 1000 — multipart
                                                  # parts each count as a field


ASGI_APPLICATION = 'simplecrm.asgi.application'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

load_dotenv()
# IMPORTANT for Celery 6+
broker_connection_retry_on_startup = True

# Optional but recommended
broker_connection_retry = True
broker_connection_max_retries = None 
AZURE_REDIS_HOST = 'whatsappnuren.redis.cache.windows.net'
AZURE_REDIS_PORT = 6379
AZURE_REDIS_PASSWORD = os.getenv('AZURE_REDIS_PASSWORD')
# Construct Redis URL
REDIS_URL = f'redis://:{AZURE_REDIS_PASSWORD}@{AZURE_REDIS_HOST}:{AZURE_REDIS_PORT}/0'

# Celery Broker and Backend Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Serialization Settings
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone Configuration
CELERY_TIMEZONE = 'UTC'

# Celery Worker Configuration
# CRITICAL: Keep this LOW to prevent database connection exhaustion
# Each worker can hold a database connection, so fewer workers = fewer connections
CELERY_WORKER_CONCURRENCY = 2  # 2 concurrent tasks (balanced with PgBouncer pooling)

# Task Routing Configuration
CELERY_TASK_ROUTES = {
    'contacts.tasks.update_contact_last_seen': {'queue': 'last_seen_updates'},
    'whatsapp_chat.tasks.process_message_status' : {'queue': 'message_status_queue'},
    'interaction.tasks.process_conversations' : {'queue': 'process_conv_queue'},
    'helpers.tasks.bulk_upload_contacts' : {'queue': 'upload_file_queue'},
}

# ============================================================================
# AZURE BLOB STORAGE CONFIGURATION
# ============================================================================
# Configuration for storing interview audio files in Azure Blob Storage
AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_STORAGE_CONNECTION_STRING', '')
AZURE_STORAGE_CONTAINER = os.getenv('AZURE_STORAGE_CONTAINER', 'media')
AZURE_STORAGE_ACCOUNT_NAME = os.getenv('AZURE_STORAGE_ACCOUNT_NAME', '')

# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'simplecrm.throttling.TenantRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'burst': '120/min',
        'sustained': '5000/day',
        'anon_burst': '30/min',
        'anon_sustained': '500/day',
        'contacts': '300/min',
        'webhook': '600/min',
        'tenant': '1000/min',
        'conversation_save': '300/min',
        'interview': '60/min',
    }
}
