# Generated by Django 4.1 on 2026-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresponse",
            name="address_audio",
            field=models.TextField(
                blank=True, help_text="Audio URL for address", null=True
            ),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="calibration_audio",
            field=models.TextField(
                blank=True, help_text="Audio URL for calibration", null=True
            ),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="name_audio",
            field=models.TextField(
                blank=True, help_text="Audio URL for name", null=True
            ),
        ),
    ]
