# Generated by Django 4.1 on 2026-02-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0004_interviewresponse_interview_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresponse",
            name="session_timestamp",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Actual session start time from conversations (for deduplication)",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_timestamp__isnull", False)),
                fields=("phone_no", "tenant", "flow_name", "session_timestamp"),
                name="unique_interview_session",
            ),
        ),
    ]
