# Generated by Django 4.1 on 2026-01-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_contact_customfield"),
        ("tenant", "0007_tenant_agents"),
        ("whatsapp_campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacts", models.ManyToManyField(blank=True, to="contacts.contact")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_group",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("template_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=50)),
                ("components", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "message_template",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("campaign_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(default="active", max_length=50)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whatsapp_campaigns.broadcastgroup",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "campaign",
            },
        ),
    ]
