# Generated by Django 4.1 on 2025-06-19 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0007_tenant_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAbits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
    ]
