# Generated by Django 4.1 on 2025-06-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wabits',
            old_name='tenant_id',
            new_name='tenant',
        ),
    ]
